version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"


  frontend:
    build: ./medicine_back/frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
